In [2]:
import numpy as np
import pandas as pd
# Task 1: NumPy Basics

# 1. Array Creation
# Create a 1D and a 2D NumPy array
ar_1=np.array([2,4,6,8])
print("1D Array is",ar_1)
ar_2= np.array([[2, 4, 6, 8], [1, 2, 3, 4]])
print("2D array is \n",ar_2)

1D Array is [2 4 6 8]
2D array is 
 [[2 4 6 8]
 [1 2 3 4]]


In [4]:
# 2. Array Operations
# Perform basic arithmetic operations on the arrays
ar_1_add=ar_1+5
print("1D array addition is ",ar_1_add)
ar_2_mul=ar_2*10
print("2D array mul is", ar_2_mul)

1D array addition is  [ 7  9 11 13]
2D array mul is [[20 40 60 80]
 [10 20 30 40]]


In [13]:
# 3. Indexing and Slicing
# Demonstrate indexing and slicing on the arrays
print("Silicing and indexing of 1D array")
print("1st element is",ar_1[0])
print("Element from 2 -3 index is",ar_1[2:])
print("Indexing of 2D array")
print("1St R 1St Col is",ar_2[0][0])
print("1st row elemet is ",ar_2[0,:])

Silicing and indexing of 1D array
1st element is 2
Element from 2 -3 index is [6 8]
Indexing of 2D array
1St R 1St Col is 2
1st row elemet is  [2 4 6 8]


In [17]:
# 4. Shape and Reshape
# Show how to check the shape of an array and reshape it
print("2D array shape is", ar_2.shape)
ar_2_reshaped=ar_2.reshape(4,2)
print("Reshaped array is", ar_2_reshaped)

2D array shape is (2, 4)
Reshaped array is [[2 4]
 [6 8]
 [1 2]
 [3 4]]


In [20]:
# Task 2: Pandas Basics
# 1. Series and DataFrame Creation
# Create a Pandas Series and DataFrame
pad_1=pd.Series([1,2,3,4,5])
print(pad_1)
dataframe_1=pd.DataFrame({
    'Name':['Ram','Sita','Gita'],
    'Age':[25,45,34]})
print(dataframe_1)


0    1
1    2
2    3
3    4
4    5
dtype: int64
   Name  Age
0   Ram   25
1  Sita   45
2  Gita   34


In [25]:
# 2. Reading Data
# Read data from a CSV file (ensure you have a sample CSV file in your repository)
read_df = pd.read_csv('data.csv')
print("Read DataFrame from CSV:\n", read_df)

Read DataFrame from CSV:
    A  B  C
0  1  4  7
1  2  5  8
2  3  6  9


In [26]:
 #3. Data Inspection
# Perform basic data inspection methods
print("Head of DataFrame:\n", read_df.head())
print("Info of DataFrame:\n", read_df.info())
print("Description of DataFrame:\n", read_df.describe())


Head of DataFrame:
    A  B  C
0  1  4  7
1  2  5  8
2  3  6  9
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes
Info of DataFrame:
 None
Description of DataFrame:
          A    B    C
count  3.0  3.0  3.0
mean   2.0  5.0  8.0
std    1.0  1.0  1.0
min    1.0  4.0  7.0
25%    1.5  4.5  7.5
50%    2.0  5.0  8.0
75%    2.5  5.5  8.5
max    3.0  6.0  9.0


In [27]:
# 4. Data Manipulation
# Selecting Data
print("Column A:\n", read_df['A'])
print("Columns A and B:\n", read_df[['A', 'B']])

Column A:
 0    1
1    2
2    3
Name: A, dtype: int64
Columns A and B:
    A  B
0  1  4
1  2  5
2  3  6


In [28]:
# Filtering Data
filtered_df = read_df[read_df['A'] > 1]
print("Filtered DataFrame (A > 1):\n", filtered_df)

Filtered DataFrame (A > 1):
    A  B  C
1  2  5  8
2  3  6  9


In [29]:
# Adding/Removing Columns
read_df['D'] = read_df['A'] + read_df['B']
print("DataFrame with new column D:\n",read_df)
read_df.drop('D', axis=1, inplace=True)
print("DataFrame after dropping column D:\n", read_df)

DataFrame with new column D:
    A  B  C  D
0  1  4  7  5
1  2  5  8  7
2  3  6  9  9
DataFrame after dropping column D:
    A  B  C
0  1  4  7
1  2  5  8
2  3  6  9


In [30]:
# Handling Missing Data
df_with_nan = read_df.copy()
df_with_nan.loc[1, 'B'] = np.nan
print("DataFrame with NaN:\n", df_with_nan)
print("DataFrame after dropping NaN:\n", df_with_nan.dropna())
print("DataFrame after filling NaN with 0:\n", df_with_nan.fillna(0))

DataFrame with NaN:
    A    B  C
0  1  4.0  7
1  2  NaN  8
2  3  6.0  9
DataFrame after dropping NaN:
    A    B  C
0  1  4.0  7
2  3  6.0  9
DataFrame after filling NaN with 0:
    A    B  C
0  1  4.0  7
1  2  0.0  8
2  3  6.0  9


In [31]:
# Task 3: Data Analysis with Pandas
# Aggregations
print("Mean of column A:", read_df['A'].mean())
print("Sum of column A:", read_df['A'].sum())


Mean of column A: 2.0
Sum of column A: 6


In [32]:
# Merging and Joining
df1 = pd.DataFrame({'key': ['A', 'B', 'C'], 'value': [1, 2, 3]})
df2 = pd.DataFrame({'key': ['A', 'B', 'D'], 'value': [4, 5, 6]})
merged_df = pd.merge(df1, df2, on='key', how='inner')
print("Merged DataFrame:\n", merged_df)


Merged DataFrame:
   key  value_x  value_y
0   A        1        4
1   B        2        5


In [34]:
# Pivot Tables
pivot_df = read_df.pivot_table(values='C', index='A', columns='B', aggfunc='mean')
print("Pivot Table:\n", pivot_df)


Pivot Table:
 B    4    5    6
A               
1  7.0  NaN  NaN
2  NaN  8.0  NaN
3  NaN  NaN  9.0


In [36]:
# Time Series Analysis
read_df['date'] = pd.date_range(start='1/1/2020', periods=len(read_df), freq='D')
read_df.set_index('date', inplace=True)
print("DataFrame with Date Index:\n",read_df)
resampled_df = read_df.resample('M').mean()
print("Resampled DataFrame:\n", resampled_df)

DataFrame with Date Index:
             A  B  C
date               
2020-01-01  1  4  7
2020-01-02  2  5  8
2020-01-03  3  6  9
Resampled DataFrame:
               A    B    C
date                     
2020-01-31  2.0  5.0  8.0


C:\Users\User\AppData\Local\Temp\ipykernel_10664\1254934817.py:5: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  resampled_df = read_df.resample('M').mean()
